spring:
  datasource:
    url: jdbc:postgresql://localhost:3600/student_management_system
    username: spring_dev
    password: spring_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG